version: '3'

services:
  app:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "7070:7070"
    depends_on:
      - database
    links:
      - database
    restart: always
  database:
    container_name: 'database'
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    restart: always